### ISSUE TITLE
Перевести БД на GSon

### ISSUE THREAD

**Issue by anry-das** [ToshnoWor/nctaskmanager#11]
Перевести БД на GSon

**Comment by anry-das** [comment]
Как вариант, можно добавить
 private static final long serialVersionUID 
для корректной сериализации классов, но это не лучшее решение т.к. при этом нужно будет каждый раз БД в стриме обновлять.

**Comment by ToshnoWor** [comment]
Issue#11: "Transfer DB to GSon"
commit: c2d6c9ee6e350568b87b2e6a3d0bd70fdcb16b0d
