### ISSUE TITLE
Пересмотреть объектную модель проекта

### ISSUE THREAD

**Issue by anry-das** [ToshnoWor/nctaskmanager#2]
Сейчас в проекте большинство методов static, что не является правилтным с т.зр. объектно ориентированного программирования. Необходимо пересмотреть структуру проекта т.о., чтобы избавиться от большинства статических методов.

**Comment by ToshnoWor** [comment]
Issue#2: "Review the project object model"
commit: 3ee8d9ad2b7c27acb3fec6f84e372a1107178654, 34f4b597bf2619f3269be4365d58d0053f0d1714
