### ISSUE TITLE
Добавить авто сохранение и авто загрузку

### ISSUE THREAD

**Issue by anry-das** [ToshnoWor/nctaskmanager#4]
Добавить сохранение данных сразу после добавления задачи. Это снизит вероятность потери данных при ошибке или неосторожном поведении пользователя. 
Добавить автоматическую загрузку данных после старта приложения.
После выполнения этих шагов можно удалить пункты Load и Save, что разгрузит интерфейс.

**Comment by ToshnoWor** [comment]
Issue#4: "Add auto save and auto load"
commit: 8946419966865461f269c961339d81627ad87e06
