### ISSUE TITLE
Замена Switch Case

### ISSUE THREAD

**Issue by anry-das** [ToshnoWor/nctaskmanager#6]
Рассмотреть возможность замены оператора выбора Switch Case например, с помощью подклассов.
Детальнее тут https://refactoring.guru/ru/replace-conditional-with-polymorphism
Также есть и др. варианты - https://overcoder.net/q/1129011/%D0%B0%D0%BB%D1%8C%D1%82%D0%B5%D1%80%D0%BD%D0%B0%D1%82%D0%B8%D0%B2%D0%B0-switch-case-%D0%B2-java

**Comment by ToshnoWor** [comment]
Issue#6: "Replacement Switch Case"
commit: bd14fab62e647d0f76ced100d5462d4fc589c4d3, 4d2fe98f105ee0c08809fcbd7e14a6b50be4d3a7
