### ISSUE TITLE
Доработать public void readOnDb

### ISSUE THREAD

**Issue by anry-das** [ToshnoWor/nctaskmanager#9]
![изображение](https://user-images.githubusercontent.com/37441696/107044197-a4c07e00-67cc-11eb-9537-79fc890b237e.png)
вот тут видно 2 проблемы:

- повторяется код (выделено красным)
- имя файла можно вынести в константу и использовать ее

**Comment by ToshnoWor** [comment]
Issue#9: "Modify public void readOnDb"
commit: ee25599cdf498896534b3f08efe3b02dabb4a4bc
